### ISSUE TITLE
Error on v4.15.0: Cannot read property 'indexOf' of undefined at Marker.normalize Arguments EventListener

### ISSUE THREAD

**Issue by tunp88** [ionic-team/ionic-native-google-maps#161] opened 2019-01-24 10:36 UTC
We are using v4.14.0 and the marker api works as well. However, when update to v4.15.0, the exception is showed: 
Cannot read property 'indexOf' of undefined at Marker.normalize Arguments EventListener

It seems that there is an issue at line 1356:
_objectInstance.__pgmId in line 1356 in file ionic-native-google-maps/src/@ionic-native/plugins/google-maps/index.ts is undefined

**Comment by wf9a5m75** [comment] 2019-01-24 14:51
The latest version is `4.20.0`

**Comment by tunp88** [comment] 2019-01-24 16:34
Thanks. I checked with version 4.20.0 and got the same problem. 
I'm moving back to version 4.14.0 and it works as well.

**Comment by wf9a5m75** [comment] 2019-01-24 16:38
Please share your project files on GitHub repository. Without valuable information, I can't check it

**Comment by tunp88** [comment] 2019-01-24 17:15
Sorry, It's our company project. I cannot share it here. But I could copy to you the stack trace:
Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at Marker.normalizeArgumentsOfEventListener (vendor.js:57856)
    at Marker.<anonymous> (vendor.js:57918)
    at Marker.trigger (:8080/plugins/cordova-plugin-googlemaps/www/BaseClass.js:71)
    at Map._onMarkerEvent (:8080/plugins/cordova-plugin-googlemaps/www/Map.js:1554)
    at Map.nativeCallback (:8080/plugins/cordova-plugin-googlemaps/www/js_CordovaGoogleMaps-for-android_ios.js:870)
    at <anonymous>:1:88
![image](https://user-images.githubusercontent.com/23456442/51695681-39b50c00-2036-11e9-9a80-e12a6043e752.png)

**Comment by wf9a5m75** [comment] 2019-01-24 17:18
Important thing is that not source code position. That information is provided at first in your report.

I need to know how to reproduce the problem. It is depends on your code and `cordova-plugin-googlemaps` version.

If you can't share your code, you can still create a new simple project.

**Comment by tunp88** [comment] 2019-01-24 17:21
I updated my note above. 
My cordova-plugin-googlemaps:
"cordova-plugin-googlemaps": "^2.4.6",

**Comment by anisseb** [comment] 2019-01-31 09:08
npm install @ionic-native/google-maps@4.14.0 --save

in order to save in package.json

**Comment by wf9a5m75** [comment] 2019-02-06 02:45
ping

**Comment by wf9a5m75** [comment] 2019-02-10 08:38
Since nobody response for a while, I close this thread.

**Closed by wf9a5m75** 2019-02-10 08:38 UTC

**Comment by HenleyCoder** [comment] 2019-02-11 22:16
I had the same error where __pgmId was undefined in normalizeArgumentsOfEventListener()
I resolved the problem by removing the Cordova-plugin-googlemaps and reinstalling it. 
I believe the cause of the problem is that in version 2.5.0 of Cordova-plugin-googlemps changed the name of a variable from __id to __pgmId. Version 4.20.0 of Ionic-native-google-maps takes this into account. However, for reasons I don't understand, even though I had updated cordova-plugin-googlemaps to version 2.5.0, I found that the version of the cordova-plugin-googlemaps  in the plugins folder had the old source code and so was still using the old variable name __id. Hence removing and reinstalling the Cordova addin resolved the problem.
